apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.nameOverride }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.nameOverride }}
    spec:
      containers:
      - name: {{ .Values.postgresql.nameOverride }}
        image: postgres:{{ .Values.postgresql.version }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresql.postgresqlPassword }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        ports:
        - containerPort: {{ .Values.postgresql.service.port }}
        volumeMounts:
        - name: {{ .Values.postgresql.nameOverride }}-data
          mountPath: /var/lib/postgresql/data
      volumes:
      {{- if .Values.postgresql.persistence.enabled }}
      - name: {{ .Values.postgresql.nameOverride }}-data
        persistentVolumeClaim:
          claimName: {{ .Values.postgresql.nameOverride }}-pvc
      {{- else }}
      - name: {{ .Values.postgresql.nameOverride }}-data
        emptyDir: {}
      {{- end }}