apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.nameOverride }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: {{ .Values.postgresql.service.port }}
    protocol: TCP
  selector:
    app: {{ .Values.postgresql.nameOverride }}